version: '2'
linters:
  default: all
  disable:
    - funlen
    - nlreturn
    - noinlineerr
    - varnamelen
    - wsl_v5
    # retired
    - exhaustruct
    - gomodguard
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: '(.+)_test\.go'
        linters:
          - lll
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - 'golang.org/x/text'
            - 'github.com/nalgeon/be'
            - 'github.com/bengarrett/binbump'
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
